/*
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ApiV1ExplorerAddressOutputs
 */
public class ApiV1ExplorerAddressOutputsTest {
    private final ApiV1ExplorerAddressOutputs model = new ApiV1ExplorerAddressOutputs();

    /**
     * Model tests for ApiV1ExplorerAddressOutputs
     */
    @Test
    public void testApiV1ExplorerAddressOutputs() {
        // TODO: test ApiV1ExplorerAddressOutputs
    }

    /**
     * Test the property 'hours'
     */
    @Test
    public void hoursTest() {
        // TODO: test hours
    }

    /**
     * Test the property 'dst'
     */
    @Test
    public void dstTest() {
        // TODO: test dst
    }

    /**
     * Test the property 'coins'
     */
    @Test
    public void coinsTest() {
        // TODO: test coins
    }

    /**
     * Test the property 'uxid'
     */
    @Test
    public void uxidTest() {
        // TODO: test uxid
    }

}
