/*
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.26.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BlockVerboseSchemaHeader
 */
public class BlockVerboseSchemaHeaderTest {
    private final BlockVerboseSchemaHeader model = new BlockVerboseSchemaHeader();

    /**
     * Model tests for BlockVerboseSchemaHeader
     */
    @Test
    public void testBlockVerboseSchemaHeader() {
        // TODO: test BlockVerboseSchemaHeader
    }

    /**
     * Test the property 'seq'
     */
    @Test
    public void seqTest() {
        // TODO: test seq
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    public void timestampTest() {
        // TODO: test timestamp
    }

    /**
     * Test the property 'fee'
     */
    @Test
    public void feeTest() {
        // TODO: test fee
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'blockHash'
     */
    @Test
    public void blockHashTest() {
        // TODO: test blockHash
    }

    /**
     * Test the property 'previousBlockHash'
     */
    @Test
    public void previousBlockHashTest() {
        // TODO: test previousBlockHash
    }

    /**
     * Test the property 'txBodyHash'
     */
    @Test
    public void txBodyHashTest() {
        // TODO: test txBodyHash
    }

    /**
     * Test the property 'uxHash'
     */
    @Test
    public void uxHashTest() {
        // TODO: test uxHash
    }

}
