/*
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.26.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineResponse2003
 */
public class InlineResponse2003Test {
    private final InlineResponse2003 model = new InlineResponse2003();

    /**
     * Model tests for InlineResponse2003
     */
    @Test
    public void testInlineResponse2003() {
        // TODO: test InlineResponse2003
    }

    /**
     * Test the property 'csrfToken'
     */
    @Test
    public void csrfTokenTest() {
        // TODO: test csrfToken
    }

}
