/*
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.ApiV1PendingTxsTransaction;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineResponse2004
 */
public class InlineResponse2004Test {
    private final InlineResponse2004 model = new InlineResponse2004();

    /**
     * Model tests for InlineResponse2004
     */
    @Test
    public void testInlineResponse2004() {
        // TODO: test InlineResponse2004
    }

    /**
     * Test the property 'announced'
     */
    @Test
    public void announcedTest() {
        // TODO: test announced
    }

    /**
     * Test the property 'isValid'
     */
    @Test
    public void isValidTest() {
        // TODO: test isValid
    }

    /**
     * Test the property 'checked'
     */
    @Test
    public void checkedTest() {
        // TODO: test checked
    }

    /**
     * Test the property 'received'
     */
    @Test
    public void receivedTest() {
        // TODO: test received
    }

    /**
     * Test the property 'transaction'
     */
    @Test
    public void transactionTest() {
        // TODO: test transaction
    }

}
