/*
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.InlineResponse2003UnconfirmedVerifyTransaction;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineResponse2003
 */
public class InlineResponse2003Test {
    private final InlineResponse2003 model = new InlineResponse2003();

    /**
     * Model tests for InlineResponse2003
     */
    @Test
    public void testInlineResponse2003() {
        // TODO: test InlineResponse2003
    }

    /**
     * Test the property 'lastReceived'
     */
    @Test
    public void lastReceivedTest() {
        // TODO: test lastReceived
    }

    /**
     * Test the property 'lastSent'
     */
    @Test
    public void lastSentTest() {
        // TODO: test lastSent
    }

    /**
     * Test the property 'outgoing'
     */
    @Test
    public void outgoingTest() {
        // TODO: test outgoing
    }

    /**
     * Test the property 'mirror'
     */
    @Test
    public void mirrorTest() {
        // TODO: test mirror
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'listenPort'
     */
    @Test
    public void listenPortTest() {
        // TODO: test listenPort
    }

    /**
     * Test the property 'isTrustedPeer'
     */
    @Test
    public void isTrustedPeerTest() {
        // TODO: test isTrustedPeer
    }

    /**
     * Test the property 'connectedAt'
     */
    @Test
    public void connectedAtTest() {
        // TODO: test connectedAt
    }

    /**
     * Test the property 'unconfirmedVerifyTransaction'
     */
    @Test
    public void unconfirmedVerifyTransactionTest() {
        // TODO: test unconfirmedVerifyTransaction
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'userAgent'
     */
    @Test
    public void userAgentTest() {
        // TODO: test userAgent
    }

    /**
     * Test the property 'height'
     */
    @Test
    public void heightTest() {
        // TODO: test height
    }

}
