/*
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ApiV1WalletTransactionHoursSelection;
import org.openapitools.client.model.ApiV1WalletTransactionTo;
import org.openapitools.client.model.ApiV1WalletTransactionWallet;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineObject
 */
public class InlineObjectTest {
    private final InlineObject model = new InlineObject();

    /**
     * Model tests for InlineObject
     */
    @Test
    public void testInlineObject() {
        // TODO: test InlineObject
    }

    /**
     * Test the property 'changeAddress'
     */
    @Test
    public void changeAddressTest() {
        // TODO: test changeAddress
    }

    /**
     * Test the property 'hoursSelection'
     */
    @Test
    public void hoursSelectionTest() {
        // TODO: test hoursSelection
    }

    /**
     * Test the property 'ignoreUnconfirmed'
     */
    @Test
    public void ignoreUnconfirmedTest() {
        // TODO: test ignoreUnconfirmed
    }

    /**
     * Test the property 'to'
     */
    @Test
    public void toTest() {
        // TODO: test to
    }

    /**
     * Test the property 'wallet'
     */
    @Test
    public void walletTest() {
        // TODO: test wallet
    }

}
