/*
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.26.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TransactionV2ParamsUnspentHoursSelection
 */
public class TransactionV2ParamsUnspentHoursSelectionTest {
    private final TransactionV2ParamsUnspentHoursSelection model = new TransactionV2ParamsUnspentHoursSelection();

    /**
     * Model tests for TransactionV2ParamsUnspentHoursSelection
     */
    @Test
    public void testTransactionV2ParamsUnspentHoursSelection() {
        // TODO: test TransactionV2ParamsUnspentHoursSelection
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'mode'
     */
    @Test
    public void modeTest() {
        // TODO: test mode
    }

    /**
     * Test the property 'shareFactor'
     */
    @Test
    public void shareFactorTest() {
        // TODO: test shareFactor
    }

}
