/*
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * TransactionVerbose has readable transaction data. It adds TransactionStatus to a BlockTransactionVerbose
 */
@ApiModel(description = "TransactionVerbose has readable transaction data. It adds TransactionStatus to a BlockTransactionVerbose")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-07-31T11:01:12.060-04:00[America/Havana]")
public class TransactionTxn {
  @JsonProperty("inner_hash")
  private String innerHash;

  @JsonProperty("inputs")
  private List<String> inputs = new ArrayList<String>();

  @JsonProperty("length")
  private Integer length;

  @JsonProperty("outputs")
  private List<Object> outputs = new ArrayList<Object>();

  @JsonProperty("sigs")
  private List<String> sigs = new ArrayList<String>();

  @JsonProperty("timestamp")
  private Long timestamp;

  @JsonProperty("txid")
  private String txid;

  @JsonProperty("type")
  private Integer type;

  public TransactionTxn innerHash(String innerHash) {
    this.innerHash = innerHash;
    return this;
  }

   /**
   * Get innerHash
   * @return innerHash
  **/
  @ApiModelProperty(value = "")
  public String getInnerHash() {
    return innerHash;
  }

  public void setInnerHash(String innerHash) {
    this.innerHash = innerHash;
  }

  public TransactionTxn inputs(List<String> inputs) {
    this.inputs = inputs;
    return this;
  }

  public TransactionTxn addInputsItem(String inputsItem) {
    if (this.inputs == null) {
      this.inputs = new ArrayList<String>();
    }
    this.inputs.add(inputsItem);
    return this;
  }

   /**
   * Get inputs
   * @return inputs
  **/
  @ApiModelProperty(value = "")
  public List<String> getInputs() {
    return inputs;
  }

  public void setInputs(List<String> inputs) {
    this.inputs = inputs;
  }

  public TransactionTxn length(Integer length) {
    this.length = length;
    return this;
  }

   /**
   * Get length
   * @return length
  **/
  @ApiModelProperty(value = "")
  public Integer getLength() {
    return length;
  }

  public void setLength(Integer length) {
    this.length = length;
  }

  public TransactionTxn outputs(List<Object> outputs) {
    this.outputs = outputs;
    return this;
  }

  public TransactionTxn addOutputsItem(Object outputsItem) {
    if (this.outputs == null) {
      this.outputs = new ArrayList<Object>();
    }
    this.outputs.add(outputsItem);
    return this;
  }

   /**
   * Get outputs
   * @return outputs
  **/
  @ApiModelProperty(value = "")
  public List<Object> getOutputs() {
    return outputs;
  }

  public void setOutputs(List<Object> outputs) {
    this.outputs = outputs;
  }

  public TransactionTxn sigs(List<String> sigs) {
    this.sigs = sigs;
    return this;
  }

  public TransactionTxn addSigsItem(String sigsItem) {
    if (this.sigs == null) {
      this.sigs = new ArrayList<String>();
    }
    this.sigs.add(sigsItem);
    return this;
  }

   /**
   * Get sigs
   * @return sigs
  **/
  @ApiModelProperty(value = "")
  public List<String> getSigs() {
    return sigs;
  }

  public void setSigs(List<String> sigs) {
    this.sigs = sigs;
  }

  public TransactionTxn timestamp(Long timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @ApiModelProperty(value = "")
  public Long getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(Long timestamp) {
    this.timestamp = timestamp;
  }

  public TransactionTxn txid(String txid) {
    this.txid = txid;
    return this;
  }

   /**
   * Get txid
   * @return txid
  **/
  @ApiModelProperty(value = "")
  public String getTxid() {
    return txid;
  }

  public void setTxid(String txid) {
    this.txid = txid;
  }

  public TransactionTxn type(Integer type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public Integer getType() {
    return type;
  }

  public void setType(Integer type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionTxn transactionTxn = (TransactionTxn) o;
    return Objects.equals(this.innerHash, transactionTxn.innerHash) &&
        Objects.equals(this.inputs, transactionTxn.inputs) &&
        Objects.equals(this.length, transactionTxn.length) &&
        Objects.equals(this.outputs, transactionTxn.outputs) &&
        Objects.equals(this.sigs, transactionTxn.sigs) &&
        Objects.equals(this.timestamp, transactionTxn.timestamp) &&
        Objects.equals(this.txid, transactionTxn.txid) &&
        Objects.equals(this.type, transactionTxn.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(innerHash, inputs, length, outputs, sigs, timestamp, txid, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionTxn {\n");
    sb.append("    innerHash: ").append(toIndentedString(innerHash)).append("\n");
    sb.append("    inputs: ").append(toIndentedString(inputs)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    outputs: ").append(toIndentedString(outputs)).append("\n");
    sb.append("    sigs: ").append(toIndentedString(sigs)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    txid: ").append(toIndentedString(txid)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

