/*
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ApiV1ExplorerAddressOutputs;

/**
 * BlockTransactionVerbose has readable transaction data for transactions inside a block. It differs from Transaction in that it includes metadata for transaction inputs and the calculated coinhour fee spent by the block
 */
@ApiModel(description = "BlockTransactionVerbose has readable transaction data for transactions inside a block. It differs from Transaction in that it includes metadata for transaction inputs and the calculated coinhour fee spent by the block")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-06-06T13:17:51.889712-04:00[America/Havana]")
public class ApiV1PendingTxsTransaction {
  public static final String SERIALIZED_NAME_OUTPUTS = "outputs";
  @SerializedName(SERIALIZED_NAME_OUTPUTS)
  private List<ApiV1ExplorerAddressOutputs> outputs = new ArrayList<ApiV1ExplorerAddressOutputs>();

  public static final String SERIALIZED_NAME_INNER_HASH = "inner_hash";
  @SerializedName(SERIALIZED_NAME_INNER_HASH)
  private String innerHash;

  public static final String SERIALIZED_NAME_INPUTS = "inputs";
  @SerializedName(SERIALIZED_NAME_INPUTS)
  private List<String> inputs = new ArrayList<String>();

  public static final String SERIALIZED_NAME_SIGS = "sigs";
  @SerializedName(SERIALIZED_NAME_SIGS)
  private List<String> sigs = new ArrayList<String>();

  public static final String SERIALIZED_NAME_LENGTH = "length";
  @SerializedName(SERIALIZED_NAME_LENGTH)
  private Integer length;

  public static final String SERIALIZED_NAME_TXID = "txid";
  @SerializedName(SERIALIZED_NAME_TXID)
  private String txid;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private Integer type;

  public static final String SERIALIZED_NAME_TIMESTAMP = "timestamp";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP)
  private Integer timestamp;

  public ApiV1PendingTxsTransaction outputs(List<ApiV1ExplorerAddressOutputs> outputs) {
    this.outputs = outputs;
    return this;
  }

  public ApiV1PendingTxsTransaction addOutputsItem(ApiV1ExplorerAddressOutputs outputsItem) {
    if (this.outputs == null) {
      this.outputs = new ArrayList<ApiV1ExplorerAddressOutputs>();
    }
    this.outputs.add(outputsItem);
    return this;
  }

   /**
   * Get outputs
   * @return outputs
  **/
  @ApiModelProperty(value = "")
  public List<ApiV1ExplorerAddressOutputs> getOutputs() {
    return outputs;
  }

  public void setOutputs(List<ApiV1ExplorerAddressOutputs> outputs) {
    this.outputs = outputs;
  }

  public ApiV1PendingTxsTransaction innerHash(String innerHash) {
    this.innerHash = innerHash;
    return this;
  }

   /**
   * Get innerHash
   * @return innerHash
  **/
  @ApiModelProperty(value = "")
  public String getInnerHash() {
    return innerHash;
  }

  public void setInnerHash(String innerHash) {
    this.innerHash = innerHash;
  }

  public ApiV1PendingTxsTransaction inputs(List<String> inputs) {
    this.inputs = inputs;
    return this;
  }

  public ApiV1PendingTxsTransaction addInputsItem(String inputsItem) {
    if (this.inputs == null) {
      this.inputs = new ArrayList<String>();
    }
    this.inputs.add(inputsItem);
    return this;
  }

   /**
   * Get inputs
   * @return inputs
  **/
  @ApiModelProperty(value = "")
  public List<String> getInputs() {
    return inputs;
  }

  public void setInputs(List<String> inputs) {
    this.inputs = inputs;
  }

  public ApiV1PendingTxsTransaction sigs(List<String> sigs) {
    this.sigs = sigs;
    return this;
  }

  public ApiV1PendingTxsTransaction addSigsItem(String sigsItem) {
    if (this.sigs == null) {
      this.sigs = new ArrayList<String>();
    }
    this.sigs.add(sigsItem);
    return this;
  }

   /**
   * Get sigs
   * @return sigs
  **/
  @ApiModelProperty(value = "")
  public List<String> getSigs() {
    return sigs;
  }

  public void setSigs(List<String> sigs) {
    this.sigs = sigs;
  }

  public ApiV1PendingTxsTransaction length(Integer length) {
    this.length = length;
    return this;
  }

   /**
   * Get length
   * @return length
  **/
  @ApiModelProperty(value = "")
  public Integer getLength() {
    return length;
  }

  public void setLength(Integer length) {
    this.length = length;
  }

  public ApiV1PendingTxsTransaction txid(String txid) {
    this.txid = txid;
    return this;
  }

   /**
   * Get txid
   * @return txid
  **/
  @ApiModelProperty(value = "")
  public String getTxid() {
    return txid;
  }

  public void setTxid(String txid) {
    this.txid = txid;
  }

  public ApiV1PendingTxsTransaction type(Integer type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public Integer getType() {
    return type;
  }

  public void setType(Integer type) {
    this.type = type;
  }

  public ApiV1PendingTxsTransaction timestamp(Integer timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @ApiModelProperty(value = "")
  public Integer getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(Integer timestamp) {
    this.timestamp = timestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiV1PendingTxsTransaction apiV1PendingTxsTransaction = (ApiV1PendingTxsTransaction) o;
    return Objects.equals(this.outputs, apiV1PendingTxsTransaction.outputs) &&
        Objects.equals(this.innerHash, apiV1PendingTxsTransaction.innerHash) &&
        Objects.equals(this.inputs, apiV1PendingTxsTransaction.inputs) &&
        Objects.equals(this.sigs, apiV1PendingTxsTransaction.sigs) &&
        Objects.equals(this.length, apiV1PendingTxsTransaction.length) &&
        Objects.equals(this.txid, apiV1PendingTxsTransaction.txid) &&
        Objects.equals(this.type, apiV1PendingTxsTransaction.type) &&
        Objects.equals(this.timestamp, apiV1PendingTxsTransaction.timestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(outputs, innerHash, inputs, sigs, length, txid, type, timestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiV1PendingTxsTransaction {\n");
    sb.append("    outputs: ").append(toIndentedString(outputs)).append("\n");
    sb.append("    innerHash: ").append(toIndentedString(innerHash)).append("\n");
    sb.append("    inputs: ").append(toIndentedString(inputs)).append("\n");
    sb.append("    sigs: ").append(toIndentedString(sigs)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    txid: ").append(toIndentedString(txid)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

