/*
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ApiV1ExplorerAddressInputs;
import org.openapitools.client.model.ApiV1ExplorerAddressOutputs;
import org.openapitools.client.model.ApiV1ExplorerAddressStatus;

/**
 * InlineResponse2002
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-06-06T13:17:51.889712-04:00[America/Havana]")
public class InlineResponse2002 {
  public static final String SERIALIZED_NAME_OUTPUTS = "outputs";
  @SerializedName(SERIALIZED_NAME_OUTPUTS)
  private List<ApiV1ExplorerAddressOutputs> outputs = new ArrayList<ApiV1ExplorerAddressOutputs>();

  public static final String SERIALIZED_NAME_INNER_HASH = "inner_hash";
  @SerializedName(SERIALIZED_NAME_INNER_HASH)
  private String innerHash;

  public static final String SERIALIZED_NAME_INPUTS = "inputs";
  @SerializedName(SERIALIZED_NAME_INPUTS)
  private List<ApiV1ExplorerAddressInputs> inputs = new ArrayList<ApiV1ExplorerAddressInputs>();

  public static final String SERIALIZED_NAME_FEE = "fee";
  @SerializedName(SERIALIZED_NAME_FEE)
  private Integer fee;

  public static final String SERIALIZED_NAME_SIGS = "sigs";
  @SerializedName(SERIALIZED_NAME_SIGS)
  private List<String> sigs = new ArrayList<String>();

  public static final String SERIALIZED_NAME_LENGTH = "length";
  @SerializedName(SERIALIZED_NAME_LENGTH)
  private Long length;

  public static final String SERIALIZED_NAME_TXID = "txid";
  @SerializedName(SERIALIZED_NAME_TXID)
  private String txid;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private Integer type;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private ApiV1ExplorerAddressStatus status = null;

  public static final String SERIALIZED_NAME_TIMESTAMP = "timestamp";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP)
  private Integer timestamp;

  public InlineResponse2002 outputs(List<ApiV1ExplorerAddressOutputs> outputs) {
    this.outputs = outputs;
    return this;
  }

  public InlineResponse2002 addOutputsItem(ApiV1ExplorerAddressOutputs outputsItem) {
    if (this.outputs == null) {
      this.outputs = new ArrayList<ApiV1ExplorerAddressOutputs>();
    }
    this.outputs.add(outputsItem);
    return this;
  }

   /**
   * Get outputs
   * @return outputs
  **/
  @ApiModelProperty(value = "")
  public List<ApiV1ExplorerAddressOutputs> getOutputs() {
    return outputs;
  }

  public void setOutputs(List<ApiV1ExplorerAddressOutputs> outputs) {
    this.outputs = outputs;
  }

  public InlineResponse2002 innerHash(String innerHash) {
    this.innerHash = innerHash;
    return this;
  }

   /**
   * Get innerHash
   * @return innerHash
  **/
  @ApiModelProperty(value = "")
  public String getInnerHash() {
    return innerHash;
  }

  public void setInnerHash(String innerHash) {
    this.innerHash = innerHash;
  }

  public InlineResponse2002 inputs(List<ApiV1ExplorerAddressInputs> inputs) {
    this.inputs = inputs;
    return this;
  }

  public InlineResponse2002 addInputsItem(ApiV1ExplorerAddressInputs inputsItem) {
    if (this.inputs == null) {
      this.inputs = new ArrayList<ApiV1ExplorerAddressInputs>();
    }
    this.inputs.add(inputsItem);
    return this;
  }

   /**
   * Get inputs
   * @return inputs
  **/
  @ApiModelProperty(value = "")
  public List<ApiV1ExplorerAddressInputs> getInputs() {
    return inputs;
  }

  public void setInputs(List<ApiV1ExplorerAddressInputs> inputs) {
    this.inputs = inputs;
  }

  public InlineResponse2002 fee(Integer fee) {
    this.fee = fee;
    return this;
  }

   /**
   * Get fee
   * @return fee
  **/
  @ApiModelProperty(value = "")
  public Integer getFee() {
    return fee;
  }

  public void setFee(Integer fee) {
    this.fee = fee;
  }

  public InlineResponse2002 sigs(List<String> sigs) {
    this.sigs = sigs;
    return this;
  }

  public InlineResponse2002 addSigsItem(String sigsItem) {
    if (this.sigs == null) {
      this.sigs = new ArrayList<String>();
    }
    this.sigs.add(sigsItem);
    return this;
  }

   /**
   * Get sigs
   * @return sigs
  **/
  @ApiModelProperty(value = "")
  public List<String> getSigs() {
    return sigs;
  }

  public void setSigs(List<String> sigs) {
    this.sigs = sigs;
  }

  public InlineResponse2002 length(Long length) {
    this.length = length;
    return this;
  }

   /**
   * Get length
   * @return length
  **/
  @ApiModelProperty(value = "")
  public Long getLength() {
    return length;
  }

  public void setLength(Long length) {
    this.length = length;
  }

  public InlineResponse2002 txid(String txid) {
    this.txid = txid;
    return this;
  }

   /**
   * Get txid
   * @return txid
  **/
  @ApiModelProperty(value = "")
  public String getTxid() {
    return txid;
  }

  public void setTxid(String txid) {
    this.txid = txid;
  }

  public InlineResponse2002 type(Integer type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public Integer getType() {
    return type;
  }

  public void setType(Integer type) {
    this.type = type;
  }

  public InlineResponse2002 status(ApiV1ExplorerAddressStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public ApiV1ExplorerAddressStatus getStatus() {
    return status;
  }

  public void setStatus(ApiV1ExplorerAddressStatus status) {
    this.status = status;
  }

  public InlineResponse2002 timestamp(Integer timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @ApiModelProperty(value = "")
  public Integer getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(Integer timestamp) {
    this.timestamp = timestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2002 inlineResponse2002 = (InlineResponse2002) o;
    return Objects.equals(this.outputs, inlineResponse2002.outputs) &&
        Objects.equals(this.innerHash, inlineResponse2002.innerHash) &&
        Objects.equals(this.inputs, inlineResponse2002.inputs) &&
        Objects.equals(this.fee, inlineResponse2002.fee) &&
        Objects.equals(this.sigs, inlineResponse2002.sigs) &&
        Objects.equals(this.length, inlineResponse2002.length) &&
        Objects.equals(this.txid, inlineResponse2002.txid) &&
        Objects.equals(this.type, inlineResponse2002.type) &&
        Objects.equals(this.status, inlineResponse2002.status) &&
        Objects.equals(this.timestamp, inlineResponse2002.timestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(outputs, innerHash, inputs, fee, sigs, length, txid, type, status, timestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2002 {\n");
    sb.append("    outputs: ").append(toIndentedString(outputs)).append("\n");
    sb.append("    innerHash: ").append(toIndentedString(innerHash)).append("\n");
    sb.append("    inputs: ").append(toIndentedString(inputs)).append("\n");
    sb.append("    fee: ").append(toIndentedString(fee)).append("\n");
    sb.append("    sigs: ").append(toIndentedString(sigs)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    txid: ").append(toIndentedString(txid)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

