/*
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ApiV1WalletsEntries;
import org.openapitools.client.model.ApiV1WalletsMeta;

/**
 * InlineResponse2005
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-06-06T13:17:51.889712-04:00[America/Havana]")
public class InlineResponse2005 {
  public static final String SERIALIZED_NAME_ENTRIES = "entries";
  @SerializedName(SERIALIZED_NAME_ENTRIES)
  private List<ApiV1WalletsEntries> entries = new ArrayList<ApiV1WalletsEntries>();

  public static final String SERIALIZED_NAME_META = "meta";
  @SerializedName(SERIALIZED_NAME_META)
  private ApiV1WalletsMeta meta = null;

  public InlineResponse2005 entries(List<ApiV1WalletsEntries> entries) {
    this.entries = entries;
    return this;
  }

  public InlineResponse2005 addEntriesItem(ApiV1WalletsEntries entriesItem) {
    if (this.entries == null) {
      this.entries = new ArrayList<ApiV1WalletsEntries>();
    }
    this.entries.add(entriesItem);
    return this;
  }

   /**
   * Get entries
   * @return entries
  **/
  @ApiModelProperty(value = "")
  public List<ApiV1WalletsEntries> getEntries() {
    return entries;
  }

  public void setEntries(List<ApiV1WalletsEntries> entries) {
    this.entries = entries;
  }

  public InlineResponse2005 meta(ApiV1WalletsMeta meta) {
    this.meta = meta;
    return this;
  }

   /**
   * Get meta
   * @return meta
  **/
  @ApiModelProperty(value = "")
  public ApiV1WalletsMeta getMeta() {
    return meta;
  }

  public void setMeta(ApiV1WalletsMeta meta) {
    this.meta = meta;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2005 inlineResponse2005 = (InlineResponse2005) o;
    return Objects.equals(this.entries, inlineResponse2005.entries) &&
        Objects.equals(this.meta, inlineResponse2005.meta);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entries, meta);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2005 {\n");
    sb.append("    entries: ").append(toIndentedString(entries)).append("\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

