/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package skycoin;

public class cipher_PubKey {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected cipher_PubKey(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(cipher_PubKey obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        skycoinJNI.delete_cipher_PubKey(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int isEqual(cipher_PubKey a) {
    return skycoinJNI.cipher_PubKey_isEqual(swigCPtr, this, cipher_PubKey.getCPtr(a), a);
  }

  public void assignFrom(cipher_PubKey data) {
    skycoinJNI.cipher_PubKey_assignFrom(swigCPtr, this, cipher_PubKey.getCPtr(data), data);
  }

  public void assignTo(cipher_PubKey data) {
    skycoinJNI.cipher_PubKey_assignTo(swigCPtr, this, cipher_PubKey.getCPtr(data), data);
  }

  public void assignSlice(GoSlice slice) {
    skycoinJNI.cipher_PubKey_assignSlice(swigCPtr, this, GoSlice.getCPtr(slice), slice);
  }

  public GoSlice toSlice() {
    return new GoSlice(skycoinJNI.cipher_PubKey_toSlice(swigCPtr, this), true);
  }

  public void setData(SWIGTYPE_p_unsigned_char value) {
    skycoinJNI.cipher_PubKey_data_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getData() {
    long cPtr = skycoinJNI.cipher_PubKey_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public cipher_PubKey() {
    this(skycoinJNI.new_cipher_PubKey(), true);
  }

}
