/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class FeeCalculator_ {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FeeCalculator_(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FeeCalculator_ obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        skycoinJNI.delete_FeeCalculator_(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCallback(SWIGTYPE_p_FeeCalcFunc value) {
    skycoinJNI.set_FeeCalculator__callback(swigCPtr, this, SWIGTYPE_p_FeeCalcFunc.getCPtr(value));
  }

  public SWIGTYPE_p_FeeCalcFunc getCallback() {
    return new SWIGTYPE_p_FeeCalcFunc(skycoinJNI.get_FeeCalculator__callback(swigCPtr, this), true);
  }

  public void setContext(SWIGTYPE_p_void value) {
    skycoinJNI.set_FeeCalculator__context(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getContext() {
    long cPtr = skycoinJNI.get_FeeCalculator__context(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public FeeCalculator_() {
    this(skycoinJNI.new_FeeCalculator_(), true);
  }

}
