/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class wallet__Note {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected wallet__Note(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(wallet__Note obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        skycoinJNI.delete_wallet__Note(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTxID(SWIGTYPE_p_GoString_ value) {
    skycoinJNI.set_wallet__Note_TxID(swigCPtr, this, SWIGTYPE_p_GoString_.getCPtr(value));
  }

  public SWIGTYPE_p_GoString_ getTxID() {
    return new SWIGTYPE_p_GoString_(skycoinJNI.get_wallet__Note_TxID(swigCPtr, this), true);
  }

  public void setValue(SWIGTYPE_p_GoString_ value) {
    skycoinJNI.set_wallet__Note_Value(swigCPtr, this, SWIGTYPE_p_GoString_.getCPtr(value));
  }

  public SWIGTYPE_p_GoString_ getValue() {
    return new SWIGTYPE_p_GoString_(skycoinJNI.get_wallet__Note_Value(swigCPtr, this), true);
  }

  public wallet__Note() {
    this(skycoinJNI.new_wallet__Note(), true);
  }

}
