/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package skycoin;

public class coin__UxOut {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected coin__UxOut(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(coin__UxOut obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        skycoinJNI.delete_coin__UxOut(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int isEqual(coin__UxOut u) {
    return skycoinJNI.coin__UxOut_isEqual(swigCPtr, this, coin__UxOut.getCPtr(u), u);
  }

  public void setHead(coin__UxHead value) {
    skycoinJNI.coin__UxOut_Head_set(swigCPtr, this, coin__UxHead.getCPtr(value), value);
  }

  public coin__UxHead getHead() {
    long cPtr = skycoinJNI.coin__UxOut_Head_get(swigCPtr, this);
    return (cPtr == 0) ? null : new coin__UxHead(cPtr, false);
  }

  public void setBody(coin__UxBody value) {
    skycoinJNI.coin__UxOut_Body_set(swigCPtr, this, coin__UxBody.getCPtr(value), value);
  }

  public coin__UxBody getBody() {
    long cPtr = skycoinJNI.coin__UxOut_Body_get(swigCPtr, this);
    return (cPtr == 0) ? null : new coin__UxBody(cPtr, false);
  }

  public coin__UxOut() {
    this(skycoinJNI.new_coin__UxOut(), true);
  }

}
