/*
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.NetworkConnectionSchema;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineResponse2004
 */
public class InlineResponse2004Test {
    private final InlineResponse2004 model = new InlineResponse2004();

    /**
     * Model tests for InlineResponse2004
     */
    @Test
    public void testInlineResponse2004() {
        // TODO: test InlineResponse2004
    }

    /**
     * Test the property 'connections'
     */
    @Test
    public void connectionsTest() {
        // TODO: test connections
    }

}
