/*
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TransactionVerifyRequest
 */
public class TransactionVerifyRequestTest {
    private final TransactionVerifyRequest model = new TransactionVerifyRequest();

    /**
     * Model tests for TransactionVerifyRequest
     */
    @Test
    public void testTransactionVerifyRequest() {
        // TODO: test TransactionVerifyRequest
    }

    /**
     * Test the property 'unsigned'
     */
    @Test
    public void unsignedTest() {
        // TODO: test unsigned
    }

    /**
     * Test the property 'encodedTransaction'
     */
    @Test
    public void encodedTransactionTest() {
        // TODO: test encodedTransaction
    }

}
