/*
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TransactionStatus
 */
public class TransactionStatusTest {
    private final TransactionStatus model = new TransactionStatus();

    /**
     * Model tests for TransactionStatus
     */
    @Test
    public void testTransactionStatus() {
        // TODO: test TransactionStatus
    }

    /**
     * Test the property 'blockSeq'
     */
    @Test
    public void blockSeqTest() {
        // TODO: test blockSeq
    }

    /**
     * Test the property 'confirmed'
     */
    @Test
    public void confirmedTest() {
        // TODO: test confirmed
    }

    /**
     * Test the property 'height'
     */
    @Test
    public void heightTest() {
        // TODO: test height
    }

    /**
     * Test the property 'unconfirmed'
     */
    @Test
    public void unconfirmedTest() {
        // TODO: test unconfirmed
    }

}
