/*
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TransactionVerboseTxnInputs
 */
public class TransactionVerboseTxnInputsTest {
    private final TransactionVerboseTxnInputs model = new TransactionVerboseTxnInputs();

    /**
     * Model tests for TransactionVerboseTxnInputs
     */
    @Test
    public void testTransactionVerboseTxnInputs() {
        // TODO: test TransactionVerboseTxnInputs
    }

    /**
     * Test the property 'uxid'
     */
    @Test
    public void uxidTest() {
        // TODO: test uxid
    }

    /**
     * Test the property 'owner'
     */
    @Test
    public void ownerTest() {
        // TODO: test owner
    }

    /**
     * Test the property 'coins'
     */
    @Test
    public void coinsTest() {
        // TODO: test coins
    }

    /**
     * Test the property 'hours'
     */
    @Test
    public void hoursTest() {
        // TODO: test hours
    }

    /**
     * Test the property 'calculatedHours'
     */
    @Test
    public void calculatedHoursTest() {
        // TODO: test calculatedHours
    }

}
