/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package skycoin.libjava;

public class api__NetworkConnectionsFilter {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected api__NetworkConnectionsFilter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(api__NetworkConnectionsFilter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        skycoinJNI.delete_api__NetworkConnectionsFilter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStates(SWIGTYPE_p_GoString_ value) {
    skycoinJNI.api__NetworkConnectionsFilter_States_set(swigCPtr, this, SWIGTYPE_p_GoString_.getCPtr(value));
  }

  public SWIGTYPE_p_GoString_ getStates() {
    return new SWIGTYPE_p_GoString_(skycoinJNI.api__NetworkConnectionsFilter_States_get(swigCPtr, this), true);
  }

  public void setDirection(SWIGTYPE_p_GoString_ value) {
    skycoinJNI.api__NetworkConnectionsFilter_Direction_set(swigCPtr, this, SWIGTYPE_p_GoString_.getCPtr(value));
  }

  public SWIGTYPE_p_GoString_ getDirection() {
    return new SWIGTYPE_p_GoString_(skycoinJNI.api__NetworkConnectionsFilter_Direction_get(swigCPtr, this), true);
  }

  public api__NetworkConnectionsFilter() {
    this(skycoinJNI.new_api__NetworkConnectionsFilter(), true);
  }

}
