/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package skyfiber.libjava;

public class bip32__PathNode {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected bip32__PathNode(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(bip32__PathNode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        skycoinJNI.delete_bip32__PathNode(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMaster(long value) {
    skycoinJNI.bip32__PathNode_Master_set(swigCPtr, this, value);
  }

  public long getMaster() {
    return skycoinJNI.bip32__PathNode_Master_get(swigCPtr, this);
  }

  public void setChildNumber(long value) {
    skycoinJNI.bip32__PathNode_ChildNumber_set(swigCPtr, this, value);
  }

  public long getChildNumber() {
    return skycoinJNI.bip32__PathNode_ChildNumber_get(swigCPtr, this);
  }

  public bip32__PathNode() {
    this(skycoinJNI.new_bip32__PathNode(), true);
  }

}
