/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package skyfiber.libjava;

public class bip32__Path {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected bip32__Path(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(bip32__Path obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        skycoinJNI.delete_bip32__Path(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setElements(SWIGTYPE_p_GoSlice_ value) {
    skycoinJNI.bip32__Path_Elements_set(swigCPtr, this, SWIGTYPE_p_GoSlice_.getCPtr(value));
  }

  public SWIGTYPE_p_GoSlice_ getElements() {
    return new SWIGTYPE_p_GoSlice_(skycoinJNI.bip32__Path_Elements_get(swigCPtr, this), true);
  }

  public bip32__Path() {
    this(skycoinJNI.new_bip32__Path(), true);
  }

}
