/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package skycoin.libjava;

public class cipher_Sig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected cipher_Sig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(cipher_Sig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        skycoinJNI.delete_cipher_Sig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int isEqual(cipher_Sig a) {
    return skycoinJNI.cipher_Sig_isEqual(swigCPtr, this, cipher_Sig.getCPtr(a), a);
  }

  public void assignFrom(SWIGTYPE_p_void data) {
    skycoinJNI.cipher_Sig_assignFrom(swigCPtr, this, SWIGTYPE_p_void.getCPtr(data));
  }

  public void assignTo(SWIGTYPE_p_void data) {
    skycoinJNI.cipher_Sig_assignTo(swigCPtr, this, SWIGTYPE_p_void.getCPtr(data));
  }

  public void setData(SWIGTYPE_p_unsigned_char value) {
    skycoinJNI.cipher_Sig_data_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getData() {
    long cPtr = skycoinJNI.cipher_Sig_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public cipher_Sig() {
    this(skycoinJNI.new_cipher_Sig(), true);
  }

}
