/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package skyfiber.libjava;

public class coin__UxHead {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected coin__UxHead(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(coin__UxHead obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        skycoinJNI.delete_coin__UxHead(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTime(java.math.BigInteger value) {
    skycoinJNI.coin__UxHead_Time_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getTime() {
    return skycoinJNI.coin__UxHead_Time_get(swigCPtr, this);
  }

  public void setBkSeq(java.math.BigInteger value) {
    skycoinJNI.coin__UxHead_BkSeq_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getBkSeq() {
    return skycoinJNI.coin__UxHead_BkSeq_get(swigCPtr, this);
  }

  public coin__UxHead() {
    this(skycoinJNI.new_coin__UxHead(), true);
  }

}
