/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package skyfiber.libjava;

public class coin_UxOutArray {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected coin_UxOutArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(coin_UxOutArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        skycoinJNI.delete_coin_UxOutArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public coin__UxOut getAt(int i) {
    long cPtr = skycoinJNI.coin_UxOutArray_getAt(swigCPtr, this, i);
    return (cPtr == 0) ? null : new coin__UxOut(cPtr, false);
  }

  public int setAt(int i, coin__UxOut uxout) {
    return skycoinJNI.coin_UxOutArray_setAt(swigCPtr, this, i, coin__UxOut.getCPtr(uxout), uxout);
  }

  public int isEqual(coin_UxOutArray a) {
    return skycoinJNI.coin_UxOutArray_isEqual(swigCPtr, this, coin_UxOutArray.getCPtr(a), a);
  }

  public void allocate(int n) {
    skycoinJNI.coin_UxOutArray_allocate(swigCPtr, this, n);
  }

  public void append(coin__UxOut uxout) {
    skycoinJNI.coin_UxOutArray_append(swigCPtr, this, coin__UxOut.getCPtr(uxout), uxout);
  }

  public void release() {
    skycoinJNI.coin_UxOutArray_release(swigCPtr, this);
  }

  public void setData(coin__UxOut value) {
    skycoinJNI.coin_UxOutArray_data_set(swigCPtr, this, coin__UxOut.getCPtr(value), value);
  }

  public coin__UxOut getData() {
    long cPtr = skycoinJNI.coin_UxOutArray_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new coin__UxOut(cPtr, false);
  }

  public void setCount(int value) {
    skycoinJNI.coin_UxOutArray_count_set(swigCPtr, this, value);
  }

  public int getCount() {
    return skycoinJNI.coin_UxOutArray_count_get(swigCPtr, this);
  }

  public coin_UxOutArray() {
    this(skycoinJNI.new_coin_UxOutArray(), true);
  }

}
