/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package skyfiber.libjava;

public class encrypt__ScryptChacha20poly1305 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected encrypt__ScryptChacha20poly1305(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(encrypt__ScryptChacha20poly1305 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        skycoinJNI.delete_encrypt__ScryptChacha20poly1305(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setN(long value) {
    skycoinJNI.encrypt__ScryptChacha20poly1305_N_set(swigCPtr, this, value);
  }

  public long getN() {
    return skycoinJNI.encrypt__ScryptChacha20poly1305_N_get(swigCPtr, this);
  }

  public void setR(long value) {
    skycoinJNI.encrypt__ScryptChacha20poly1305_R_set(swigCPtr, this, value);
  }

  public long getR() {
    return skycoinJNI.encrypt__ScryptChacha20poly1305_R_get(swigCPtr, this);
  }

  public void setP(long value) {
    skycoinJNI.encrypt__ScryptChacha20poly1305_P_set(swigCPtr, this, value);
  }

  public long getP() {
    return skycoinJNI.encrypt__ScryptChacha20poly1305_P_get(swigCPtr, this);
  }

  public void setKeyLen(long value) {
    skycoinJNI.encrypt__ScryptChacha20poly1305_KeyLen_set(swigCPtr, this, value);
  }

  public long getKeyLen() {
    return skycoinJNI.encrypt__ScryptChacha20poly1305_KeyLen_get(swigCPtr, this);
  }

  public encrypt__ScryptChacha20poly1305() {
    this(skycoinJNI.new_encrypt__ScryptChacha20poly1305(), true);
  }

}
