/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package skycoin.libjava;

public class Fee_Calculator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Fee_Calculator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Fee_Calculator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        skycoinJNI.delete_Fee_Calculator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCallback(SWIGTYPE_p_f_Transaction__Handle_p_unsigned_long_long_p_void__GoUint32_ value) {
    skycoinJNI.Fee_Calculator_callback_set(swigCPtr, this, SWIGTYPE_p_f_Transaction__Handle_p_unsigned_long_long_p_void__GoUint32_.getCPtr(value));
  }

  public SWIGTYPE_p_f_Transaction__Handle_p_unsigned_long_long_p_void__GoUint32_ getCallback() {
    long cPtr = skycoinJNI.Fee_Calculator_callback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_Transaction__Handle_p_unsigned_long_long_p_void__GoUint32_(cPtr, false);
  }

  public void setContext(SWIGTYPE_p_void value) {
    skycoinJNI.Fee_Calculator_context_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getContext() {
    long cPtr = skycoinJNI.Fee_Calculator_context_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public Fee_Calculator() {
    this(skycoinJNI.new_Fee_Calculator(), true);
  }

}
