/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package skycoin.libjava;

public class secp256k1go__XY {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected secp256k1go__XY(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(secp256k1go__XY obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        skycoinJNI.delete_secp256k1go__XY(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(secp256k1go__Field value) {
    skycoinJNI.secp256k1go__XY_X_set(swigCPtr, this, secp256k1go__Field.getCPtr(value), value);
  }

  public secp256k1go__Field getX() {
    long cPtr = skycoinJNI.secp256k1go__XY_X_get(swigCPtr, this);
    return (cPtr == 0) ? null : new secp256k1go__Field(cPtr, false);
  }

  public void setY(secp256k1go__Field value) {
    skycoinJNI.secp256k1go__XY_Y_set(swigCPtr, this, secp256k1go__Field.getCPtr(value), value);
  }

  public secp256k1go__Field getY() {
    long cPtr = skycoinJNI.secp256k1go__XY_Y_get(swigCPtr, this);
    return (cPtr == 0) ? null : new secp256k1go__Field(cPtr, false);
  }

  public void setInfinity(long value) {
    skycoinJNI.secp256k1go__XY_Infinity_set(swigCPtr, this, value);
  }

  public long getInfinity() {
    return skycoinJNI.secp256k1go__XY_Infinity_get(swigCPtr, this);
  }

  public secp256k1go__XY() {
    this(skycoinJNI.new_secp256k1go__XY(), true);
  }

}
