/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package skycoin.libjava;

public class wallet_register {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected wallet_register(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(wallet_register obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        skycoinJNI.delete_wallet_register(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setClient(SWIGTYPE_p_Client__Handle value) {
    skycoinJNI.wallet_register_client_set(swigCPtr, this, SWIGTYPE_p_Client__Handle.getCPtr(value));
  }

  public SWIGTYPE_p_Client__Handle getClient() {
    return new SWIGTYPE_p_Client__Handle(skycoinJNI.wallet_register_client_get(swigCPtr, this), true);
  }

  public void setWallet(SWIGTYPE_p_WalletResponse__Handle value) {
    skycoinJNI.wallet_register_wallet_set(swigCPtr, this, SWIGTYPE_p_WalletResponse__Handle.getCPtr(value));
  }

  public SWIGTYPE_p_WalletResponse__Handle getWallet() {
    return new SWIGTYPE_p_WalletResponse__Handle(skycoinJNI.wallet_register_wallet_get(swigCPtr, this), true);
  }

  public wallet_register() {
    this(skycoinJNI.new_wallet_register(), true);
  }

}
