/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package skyfiber.libjava;

public class wallet__ReadableNote {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected wallet__ReadableNote(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(wallet__ReadableNote obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        skycoinJNI.delete_wallet__ReadableNote(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTransactionID(SWIGTYPE_p_GoString_ value) {
    skycoinJNI.wallet__ReadableNote_TransactionID_set(swigCPtr, this, SWIGTYPE_p_GoString_.getCPtr(value));
  }

  public SWIGTYPE_p_GoString_ getTransactionID() {
    return new SWIGTYPE_p_GoString_(skycoinJNI.wallet__ReadableNote_TransactionID_get(swigCPtr, this), true);
  }

  public void setActualNote(SWIGTYPE_p_GoString_ value) {
    skycoinJNI.wallet__ReadableNote_ActualNote_set(swigCPtr, this, SWIGTYPE_p_GoString_.getCPtr(value));
  }

  public SWIGTYPE_p_GoString_ getActualNote() {
    return new SWIGTYPE_p_GoString_(skycoinJNI.wallet__ReadableNote_ActualNote_get(swigCPtr, this), true);
  }

  public wallet__ReadableNote() {
    this(skycoinJNI.new_wallet__ReadableNote(), true);
  }

}
