/*
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TransactionV2ParamsUnspentTo
 */
public class TransactionV2ParamsUnspentToTest {
    private final TransactionV2ParamsUnspentTo model = new TransactionV2ParamsUnspentTo();

    /**
     * Model tests for TransactionV2ParamsUnspentTo
     */
    @Test
    public void testTransactionV2ParamsUnspentTo() {
        // TODO: test TransactionV2ParamsUnspentTo
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'coins'
     */
    @Test
    public void coinsTest() {
        // TODO: test coins
    }

}
