/*
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for WalletTransactionSignRequest
 */
public class WalletTransactionSignRequestTest {
    private final WalletTransactionSignRequest model = new WalletTransactionSignRequest();

    /**
     * Model tests for WalletTransactionSignRequest
     */
    @Test
    public void testWalletTransactionSignRequest() {
        // TODO: test WalletTransactionSignRequest
    }

    /**
     * Test the property 'walletId'
     */
    @Test
    public void walletIdTest() {
        // TODO: test walletId
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

    /**
     * Test the property 'encodedTransaction'
     */
    @Test
    public void encodedTransactionTest() {
        // TODO: test encodedTransaction
    }

    /**
     * Test the property 'signIndexes'
     */
    @Test
    public void signIndexesTest() {
        // TODO: test signIndexes
    }

}
